name: "Update flake dependencies"
on:
  push:
  schedule:
    - cron: '30 1 * * */3'
jobs:
  updateflake:
    if: (startsWith(github.event.head_commit.message, 'update:') || (github.event_name == 'schedule'))
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        # Nix Flakes doesn't work on shallow clones
        fetch-depth: 0
    - name: Install nixFlake
      uses: cachix/install-nix-action@v10
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-3.0pre20200820_4d77513/install
    - name: Configure Nix to enable flake
      run: echo "experimental-features = nix-command flakes" | sudo tee -a /etc/nix/nix.conf
    - name: Update flake.lock
      id: update
      run: nix flake update --recreate-lock-file
    - name: Commit changes
      run: |
        git status
        echo "git status done."
        git config --global user.name 'GitHub Action - Harry Ying'
        git config --global user.email 'LEXUGEyky@outlook.com'
        git commit -am "Update flake.lock - automated"
        git push || true
